// This file is generated by drizzle-kit.
// Run `npm run db:generate` to populate it, then restart your app.
//
// After generating, this file will be replaced by drizzle-kit with the
// actual migration journal and SQL statements bundled for expo-sqlite.

export default { journal: { entries: [] as never[] }, migrations: {} as Record<string, string> };
